import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { MonitorSmartphone, ShoppingCart } from 'lucide-react';
import Link from 'next/link';


const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children, //slot for children
  ads //slot for ads
}: Readonly<{
  children: React.ReactNode;
  ads?: React.ReactNode;
}>)

 {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <main className='flex justify-between flex-col min-h-screen'>
          <header className='flex justify-between items-center shadow-xl bg-white h-16 w-full px-24 fixed z-20'>
            <div className='flex items-center gap-3'>
              <MonitorSmartphone/>
              <Link href="/" className='font-bold text-2xl'>Sopapp</Link>
            </div>
            <div>
              <ShoppingCart/>
            </div>
          </header>
          <div className="px-20 mt-20">{children}</div>
          <div className='my-10 mx-auto flex justify-center'> 
           {ads}
            </div>
        <footer className='bg-black w-full h-10 text-white flex justify-center items-center'>
          <p>info@donyayelee.com</p>
        </footer>
        </main>
      </body>
    </html>
  );
}
